import required packages

In [1]:
import pathlib
import random
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import rioxarray as rioxr
import geopandas as gpd

In [ ]:
config = {'inputDirectory':'',
 'outputDirectory':'',         
 'bands':[1,2,3],
 'sizeCutOut':20,
 'nEpochMax':2,
 'sizeStep':5}

In [ ]:
def create_input_list(inputDir):
    inputList = [t for t in pathlib.Path(inputDir).glob('*.tif')]
    return inputList

In [ ]:
def read_config(config):
    if pathlib.Path(config).is_file():
        raise NotImplementedError()
        
    else :
        inputDir = config['inputDirectory']
        outputDir = config['outputDirectory']
        bands = config['bands']
        sizeCutOut = config['sizeCutOut']
        nEpochMax = config['nEpochMax']
        sizeStep = config['sizeStep']
        
    return inputDir, outputDir, bands, sizeCutOut, nEpochmax, sizeStep

define Dataset class and methods

In [ ]:
class Dataset:
    
    def __init__(self, tile_list, cutout_size, bands, offset=0, stride=None, num_tiles=None, shuffle_tiles=False):
        self.cutout_size = cutout_size
        self.bands = bands
        self.stride = stride if stride is not None else self.cutout_size
        _num_tiles = num_tiles if num_tiles is not None else len(tile_list)
        self.tiles = random.sample(tile_list, _num_tiles) if shuffle_tiles else tile_list[:_num_tiles]
        if offset >= cutout_size:
            raise ValueError(
                "offset larger than window size - set "
                "offset to {}".format(sizeCutOut%offset)
            )
        self.offset = offset
        
        self.mask = None
        self.buffer = None
        self.invert = None
        self.all_touched = None
    
    def set_mask(self, geometry, crs, buffer=None, invert=False, all_touched=False):
        """ Mask a selection of the pixels using a geometry."""
        self.mask = gpd.GeoSeries({"geometry": geometry}, crs=crs)
        self.buffer = buffer if buffer is not None else 0
        self.invert = invert
        self.all_touched = all_touched
    
    def to_tf(self):
        """ Obtain dataset as a tensorflow `Dataset` object. """
        ds = tf.data.Dataset.from_generator(
            self._generate_cutouts,  
            output_types=(tf.float64, tf.float64, tf.float32), 
            output_shapes=(
                None,  # x
                None,  # y
                (None, None, self.cutout_size, self.cutout_size)  # samples, bands, x_win, y_win
            )
        )
        return ds.flat_map(lambda x,y,z: tf.data.Dataset.from_tensor_slices((x,y,z)))

    def _generate_cutouts(self):
        """ 
        Iterate over (a selection of) the tiles yielding all 
        cutouts for each of them.
        """
        for tile in self.tiles:
            
            print(f"Reading tile {tile}!")
            
            # read tile
            da = rioxr.open_rasterio(tile).astype("float32")  # needed to mask with NaN's
            
            #select bands
            if self.bands is not None:
                if type(self.bands) is not list:
                    da = da.sel(band=[self.bands])
                else:
                    da = da.sel(band=self.bands)
                    
                
            
            if self.mask is not None:
                mask = self.mask.to_crs(da.spatial_ref.crs_wkt)
                geometry = mask.unary_union.buffer(self.buffer)
                da = da.rio.clip([geometry], drop=True, invert=self.invert, all_touched=self.all_touched)
            
            # apply offset
            da = da.shift(x=self.offset, y=self.offset)  # only shift data, not coords
            da['x'] = da.x.shift(x=self.offset)
            da['y'] = da.y.shift(y=self.offset)

            # generate windows
            da = da.rolling(x=self.cutout_size, y=self.cutout_size)
            da = da.construct({'x': 'x_win', 'y': 'y_win'}, stride=self.stride)

            # drop NaN-containing windows
            da = da.stack(sample=('x', 'y'))
            da = da.dropna(dim='sample', how='any')
            yield (da.sample.coords['x'], 
                   da.sample.coords['y'], 
                   da.data.transpose(3, 1, 2, 0))  # samples, x_win, y_win, bands

### Begin feedloop

In [ ]:
inputDir, outputDir, _, sizeCutOut, nEpochmax, sizeStep = read_config(config)

In [ ]:
inputList = create_input_list(inputDir)

In [ ]:
epochCounter = 0

In [ ]:
gdf = gpd.read_file("ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp")


In [ ]:
while epochcounter < nEpochsMax:
    offset = epochcounter*sizeStep
    #randomly permutate inputList for each epoch
    inputList = list(np.random.permutation(inpuList))
    #construct Dataset
    inData = Dataset(inputList,sizeCutOut,offset=offset)
    inData.set_mask(gdf.unary_union, crs=gdf.crs)
    dataSet = inData.to_tf()
    
    """
    this buffersize sould correpond to 6 full tiles, 
    so 7 in total in memory
    """ 
    dataSet.shuffle(buffersize=3000000).batch(64,drop_remainder=True)
    
    """
    network to be addded below
    """
    #network here
       #input
        
       #save network
       #outputDir has been specified in config
        
       #early stopping ?
    
    #repeat from here
        
    epochcounter+=1
    

In [16]:
type(b)

str

In [13]:
a[0]

TypeError: 'int' object is not subscriptable

In [15]:
if type(b) == int: print('yes')

In [25]:
tt = rioxr.open_rasterio('/Users/eslt0101/Data/eScience/IceShelves/TestDataSet/S2_20180127T151251_20180127T151254_T14CMB.tif').astype('float32')

In [29]:
tt.sel(band=[1])

<xarray.DataArray (band: 1, y: 5749, x: 5152)>
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)
Coordinates:
  * band         (band) int64 1
  * y            (y) float64 0.5 1.5 2.5 3.5 ... 5.746e+03 5.748e+03 5.748e+03
  * x            (x) float64 0.5 1.5 2.5 3.5 ... 5.15e+03 5.15e+03 5.152e+03
    spatial_ref  int64 0
Attributes:
    STATISTICS_MAXIMUM:  255
    STATISTICS_MEAN:     33.457891959433
    STATISTICS_MINIMUM:  0
    STATISTICS_STDDEV:   60.888320883306
    scale_factor:        1.0
    add_offset:          0.0
    grid_mapping:        spatial_ref

In [23]:
tt

<xarray.DataArray (y: 5749, x: 5152)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
Coordinates:
    band         int64 1
  * y            (y) float64 0.5 1.5 2.5 3.5 ... 5.746e+03 5.748e+03 5.748e+03
  * x            (x) float64 0.5 1.5 2.5 3.5 ... 5.15e+03 5.15e+03 5.152e+03
    spatial_ref  int64 0
Attributes:
    STATISTICS_MAXIMUM:  255
    STATISTICS_MEAN:     33.457891959433
    STATISTICS_MINIMUM:  0
    STATISTICS_STDDEV:   60.888320883306
    scale_factor:        1.0
    add_offset:          0.0
    grid_mapping:        spatial_ref

<xarray.DataArray (band: 3, y: 5749, x: 5152)>
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)
Coordinates:
  * band         (band) int64 1 2 3
  * y            (y) float64 0.5 1.5 2.5 3.5 ... 5.746e+03 5.748e+03 5.748e+03
  * x            (x) float64 0.5 1.5 2.5 3.5 ... 5.15e+03 5.15e+03 5.152e+03
    spatial_ref  int64 0
Attributes:
    STATISTICS_MAXIMUM:  255
    STATISTICS_MEAN:     33.457891959433
    STATISTICS_MINIMUM:  0
    STATISTICS_STDDEV:   60.888320883306
    scale_factor:        1.0
    add_offset:          0.0
    grid_mapping:        spatial_ref